#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Generate Standard Bash Configurations (added to chezmoi source)
# -----------------------------------------------------------------------------
echo "📝 Generating standard Bash configuration files..."

# 1. .bash_profile
cat << 'EOF' > dot_bash_profile
# .bash_profile

# 1. Source .bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

# 2. Include user's private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi

# 3. Source the exports file generated by bootstrap.sh
if [ -f "$HOME/.config/shell/exports.sh" ]; then
    . "$HOME/.config/shell/exports.sh"
fi
EOF

# 2. .bashrc
cat << 'EOF' > dot_bashrc
# .bashrc

# 1. Exit early if not running interactively
case $- in
    *i*) ;;
      *) return;;
esac

# 2. History Settings
# Don't put duplicate lines or lines starting with space in the history.
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=10000
export HISTFILESIZE=20000
shopt -s histappend

# 3. Window Size & Globbing
# Update the values of LINES and COLUMNS after each command
shopt -s checkwinsize
# recursive globbing (e.g. ls **/*.py)
shopt -s globstar

# 4. Colors
export TERM=xterm-256color
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# 5. Load Aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# 6. Bash Completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# 7. Source shared exports (created by bootstrap.sh)
if [ -f "$HOME/.config/shell/exports.sh" ]; then
    . "$HOME/.config/shell/exports.sh"
fi

# 8. Tool Activation (Mise & Starship)
# Your bootstrap script checks for these lines; keeping them here ensures idempotency.
if command -v mise &> /dev/null; then
  eval "$(mise activate bash)"
fi

if command -v starship &> /dev/null; then
  eval "$(starship init bash)"
fi
EOF

# 3. .bash_aliases
cat << 'EOF' > dot_bash_aliases
# .bash_aliases

# --- Navigation ---
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'

# --- Listing ---
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# --- Safety ---
# Prompt before overwriting/deleting
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'

# --- Modern Tool Replacements ---
# Use vim as default if installed
if command -v vim &> /dev/null; then
  alias vi='vim'
# Fallback to neovim if vim is missing
elif command -v nvim &> /dev/null; then
  alias vim='nvim'
  alias vi='nvim'
fi

# Use bat instead of cat (Ubuntu installs it as batcat)
if command -v batcat &> /dev/null; then
  alias cat='batcat'
elif command -v bat &> /dev/null; then
  alias cat='bat'
fi

# Use fdfind as fd (Ubuntu installs it as fdfind)
if command -v fdfind &> /dev/null; then
  alias fd='fdfind'
fi

# --- Git Shortcuts ---
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'

# --- Utils ---
alias reload='source ~/.bashrc'
alias path='echo -e ${PATH//:/\\n}'
alias cls='clear'

# --- RBK Aliases ---  ADJUST the following aliases to your needs as it has RBK's specific aliases.
alias repo='cd ~/repos'
alias dot='cd ~/repos/github/rbk-dotfiles'
alias rbk='cd ~/repos/github/bharthu58.github.io'
alias ai='cd ~/repos/github/rbk-ai-projects'
alias app='cd ~/repos/github/rbk-cpp-projects'
alias py='cd ~/repos/github/rbk-python-projects'
alias web='cd ~/repos/github/rbk-web-projects'
EOF
